services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data: # This ensures your database data isn't lost if the container stops