services:

  frontend:
    image: frontend:latest
    container_name: local-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
  
  backend:
    image: backend:latest
    container_name: local-backend
    ports:
      - "5001:5001"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data: # This ensures your database data isn't lost if the container stops